### ISSUE TITLE
CPU使用率について

### ISSUE THREAD

**Issue by surume-ika** [noda-sin/ebisu#3]
@noda-sin 様　先日はありがとうございました！無事に稼働しております！

CPU稼働率についてお伺いしたいのですが、
AWSで実行時CPUが99%に張り付く感じクレジットが減り動作が重くなってしまいました。
(Nohup にしておりました)

なので、GCPだとどうなのだろうと思い移行してみましたが、

GCP  (g1-small（vCPU x 1、メモリ 1.7 GB）)
- - PS AUX
root     24559 99.6  5.6 489132 96924 ?        Rl   10:32 133:38 python3.6 main.py --strategy Doten

![gcp](https://user-images.githubusercontent.com/34591218/43031819-9876464a-8ce4-11e8-9de2-c32ba531291e.png)

同じ感じで、モニタリングでもCPUは100%近い感じでした。

CPUクレジットが思ったより減る感じになっていたので、
なんとか回避できる技はあるのでしょうか。

Nohupでしているからこのような稼働率になってしまうのでしょうか。
もし何か思いつく事などあればお伺いしたいです！

よろしくお願いいたします。

**Comment by surume-ika** [comment]
@noda-sin 様　
早急なご対応本当にありがとうございます！本当にすごいです。感動です。
一気に下がりました！！！これで動かし続けてみます！他のストラテジーも近々トライしてみたいと思います！
おかげで楽しみがいっぱい増えました！！

AWS t2.micro - - 

![aws](https://user-images.githubusercontent.com/34591218/43034734-02a9c8e2-8d1d-11e8-9f08-173fc5b37fc5.png)

root      2867  1.6  9.6 458836 97864 pts/0    Sl   19:29   0:02 python3.6 main.py --strategy Doten

**Comment by noda-sin** [comment]
@surume-ika さん
なおったとのこと、よかったです。
ストラテジーですが恐らくご存知かと思いますが、かなり有名なものなので、もしかしたら儲からないかもしれません。ご了承ください。
このBotは、どちらかというと戦略を追加しやすいように作られたFramework的なものなので、アイディアなどあれば追加してみてくださいね。
